### ISSUE TITLE
Hide HTML

### ISSUE THREAD

**Issue by BlackIQ** [ThevergeOn/ThevergeOn#1]
Hi,

I have 2 ideas and just wanted to share with you.

- Hiding languages
- Count of languages

### Hiding languages

You know HTML files are larger than other files and in counting them, it gets most part of the top languages status.

I suggest to hide this language by adding a GET method named `hide`. Example:

`&hide=html`

Or for more languages, add a `,` and tell them. Example:

`&hide=html,css,sass,markdown`

### Counting languages

You can show more or less languages. Just add `langs_count` and tell the count of them. Example:

`&langs_count=10`

`&langs_count=5`

Default is 4. Maximum is 10.

Just them. Live long and prosper.

Amir.

**Comment by ThevergeOn** [comment]
That's a good idea. I just did it
Thanks :)

**Comment by vonshirco** [comment]
Very helpful, thanks
